name: shine
description: 'developing...'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  concert:
    path: ../concert
  
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2
  path: ^1.9.0
  get: ^4.6.6
  adaptive_dialog: ^2.1.0
  file_picker: ^8.0.3
  uuid: ^4.4.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  open_file_manager: ^1.0.2
  flutter_easyloading: ^3.0.5
  filesaverz: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  fonts:
    - family: HarmonyOS Sans
      fonts:
        - asset: fonts/HarmonyOS_Sans_SC_Regular.ttf
